version: "3.9"

services:
  meilisearch:
    image: getmeili/meilisearch:v1.3
    container_name: meilisearch
    restart: always
    ports:
      - 7700:7700
    environment:
      - MEILI_ENV=development
    volumes:
      - ${PWD}/db/meili:/meili_data
    command: meilisearch --master-key="ThisIsMasterKey"